### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by rogldicksn** [Fornball/fornballs-btc-stealer#2]
i get this errors 

any possible solutions ?

![image](https://user-images.githubusercontent.com/76434629/152657785-e5b9cb98-b57b-4502-aab9-3e0f95b85872.png)

**Comment by Fornball** [comment]
First of all, this project is not finished. 

So error 404 means "couldnt reach website". Probably it somehow generated an unexisting wallet? Or u have no internet/unreliable/the blockchair website is blocked.
If u open ur browser, does [this](https://www.blockchain.com/btc/address/19dENFt4wVwos6xtgwStA6n8bbA57WCS58) url work?

**Comment by rogldicksn** [comment]
yes the link opens very well, it opens alright and i have good internet too

**Comment by rogldicksn** [comment]
it works when i input below 20 wallets to check .. above 20 it doesn't and infinity also doesn't work

**Comment by Fornball** [comment]
well, Im gonna maybe improve this project later. Tho keep in mind, the whole project is kinda stupid.

**Comment by rogldicksn** [comment]
lol..

why is it stupid.. does it not work as mentioned ?

**Comment by Fornball** [comment]
It (sometimes) does but the concept is stupid

**Comment by Fornball** [comment]
Well, to be precise. The idea is that it generates a wallet, then checks online if the wallet has any balance. This takes way too long. What would be smarter, would be to download a list of all btc wallets with a balance and then run the checks locally.
